import React, { PropsWithChildren } from 'react';
import * as icons from '.';

export const iconMap = {
  ICON_AccountCircle: <icons.ICON_AccountCircle />,
  ICON_Add: <icons.ICON_Add />,
  ICON_Check: <icons.ICON_Check />,
  ICON_Checkbox: <icons.ICON_Checkbox />,
  ICON_Circle: <icons.ICON_Circle />,
  ICON_Close: <icons.ICON_Close />,
  ICON_Collapse: <icons.ICON_Collapse />,
  ICON_Delete: <icons.ICON_Delete />,
  ICON_Dns: <icons.ICON_Dns />,
  ICON_Drag: <icons.ICON_Drag />,
  ICON_Edit: <icons.ICON_Edit />,
  ICON_EditOff: <icons.ICON_EditOff />,
  ICON_Expand: <icons.ICON_Expand />,
  ICON_Info: <icons.ICON_Info />,
  ICON_Lock: <icons.ICON_Lock />,
  ICON_Menu: <icons.ICON_Menu />,
  ICON_More: <icons.ICON_More />,
  ICON_Next: <icons.ICON_Next />,
  ICON_Open: <icons.ICON_Open />,
  ICON_Pause: <icons.ICON_Pause />,
  ICON_PhotoCamera: <icons.ICON_PhotoCamera />,
  ICON_Play: <icons.ICON_Play />,
  ICON_Prev: <icons.ICON_Prev />,
  ICON_Record: <icons.ICON_Record />,
  ICON_Refresh: <icons.ICON_Refresh />,
  ICON_Save: <icons.ICON_Save />,
  ICON_Search: <icons.ICON_Search />,
  ICON_Square: <icons.ICON_Square />,
  ICON_Stop: <icons.ICON_Stop />,
  ICON_Tag: <icons.ICON_Tag />,
  ICON_Tag_Outline: <icons.ICON_Tag_Outline />,
  ICON_UploadFile: <icons.ICON_UploadFile />,
  ICON_Visibility: <icons.ICON_Visibility />,
  ICON_VisibilityOff: <icons.ICON_VisibilityOff />,
} as any;
